kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
- role: worker
networking:
  disableDefaultCNI: true # disable the default Kindnet CNI
  podSubnet: 192.168.0.0/16 # set to Calico's default subnet
